version: '3.9'
services:
  backend:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    # restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: supersecret
    volumes:
      - .mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080

